### ISSUE TITLE
Missing stat for 2 players in game 20191028/0021900042

### ISSUE THREAD

**Issue by polypolo55** [jasonroman/nba-stats-api#10]
On a specific game on Monday 2019-10-28, game CHI@NYK (gameID = 0021900042)
https://data.nba.net/10s/prod/v1/20191028/0021900042_boxscore.json

We found that Otto Porter Jr. and Wendel Carter Jr. are both marked as they did not play ( "DNP - Injury / Illness" ) but in the reality they have played this game.
Consequences : No stat are reported for these players.

Wondering if you had this kind of problem before and if it's easy to fix ;)

Thanks

**Comment by jasonroman** [comment]
Hello,

My API is only a tool to access NBA stats.  If there are data issues only the NBA can fix them on their end.

Thanks,
-Jason
