### ISSUE TITLE
cannot retrieve a boxscore for Game ID 0021900053

### ISSUE THREAD

**Issue by polypolo55** [jasonroman/nba-stats-api#11]
Hi, 
there is a problem with the following JSON, 
http://data.nba.net/10s/prod/v1/20191029/0021900053_boxscore.json

It miss all  boxscore for this game -> basically the "stats" section.

Can you do something about it ?

**Comment by jasonroman** [comment]
Hello,

I have nothing to do with the actual data returned from any of these requests.  My API is just a way to more easily retrieve data from the NBA.
