### ISSUE TITLE
standings_all request with date paremeter is failing with dates higher than 201903111 

### ISSUE THREAD

**Issue by victorMaestro1994** [jasonroman/nba-stats-api#13]
Hello!

standings_all request with date paremeter is failing with dates higher than 201903111

Example:
This work:
http://data.nba.net/prod/v1/201903110/standings_all.json

But when I try it with higher dates: HTTP ERROR 404
http://data.nba.net/prod/v1/201903111/standings_all.json

Thanks and regards
have a nice day :)

**Comment by jasonroman** [comment]
Hello,

Unfortunately I have no control over what data or URLs are valid; my API is merely a tool to access statistics from public NBA sources.  The NBA can change this at any time.

Sometimes data does not work one day and then works the next.  For this individual instance there is a decent chance the NBA stopped using this data point and no longer updated it after that date.

Hope that helps!
