### ISSUE TITLE
Playoffs Schedule and Updated Roster for Teams

### ISSUE THREAD

**Issue by mayanaor** [jasonroman/nba-stats-api#15]
Couldn't find a place in the API where I can get Playoffs Schedule. Do you have plans on adding it?
Also - roster data for teams is not up to date through this endpoint: "http://data.nba.net/json/cms/noseason/team/wizards/roster.json"
Is there another endpoint one can get the updated roster from?

**Comment by jasonroman** [comment]
Hello,

This API is only a gateway to data that the NBA provides, it is not the provider of the data itself. As for the roster you may want to look at http://nbasense.com/nba-api/Stats/Stats/Roster/TeamRoster which accesses http://stats.nba.com/stats/commonteamroster/
