### ISSUE TITLE
Api.nba.net video endpoint not working

### ISSUE THREAD

**Issue by ghost** [jasonroman/nba-stats-api#4]
On your website it works perfectly and returns all the videos of a game, but when I'm trying to open the link in my browser or in my application I get error response. 
What am i doing wrong?

**Comment by ghost** [comment]
ok i got this working the example in your site have a spare slash after the video endpoint

**Comment by jasonroman** [comment]
Glad you got it working!

**Comment by ghost** [comment]
and by the way i found the way to get the last n collections.
api.nba.net/0/league/collection?count=n
Thats works also with the article and the video endpoints.
And the article endpoint can work like the video and show the articles of a particular game
api.nba.net/0/league/article?games=x&count=n
