### ISSUE TITLE
Is real time game data available?

### ISSUE THREAD

**Issue by jarvis-wu** [jasonroman/nba-stats-api#5]
Hi, thank you so much for providing this api. I'm currently working on an iOS project, and I would like to update live data (specifically, all 3-pointers players made) when a game is playing. Is it possible to get play-by-play or something like 3PT shoots in real time?

Thanks!

**Comment by jasonroman** [comment]
Hi Jarvis,

I believe the endpoints from data.nba.net update fairly quickly in real-time and some of the stats.nba.com data points return data in real-time as well. I would look at the individual game endpoints within there and play around with that data.
