### ISSUE TITLE
Could i use this api on my application?

### ISSUE THREAD

**Issue by Mrtckr008** [jasonroman/nba-stats-api#6]
Could i use this api on my android application? I mean, Should i share API's owner's name or something like that(etc permission for use) in my app? Also are these APIs work to all of time?

**Comment by jasonroman** [comment]
Hello,

This software is released under the MIT License: https://github.com/jasonroman/nba-api/blob/master/LICENSE and a decent explanation is found here: https://softwareengineering.stackexchange.com/a/178493/162210

I do not want to give legal advice but essentially yes you would need to include that the software uses this library and include its copyright notice.  I'm not sure what your second question is asking - these APIs are used as to access the NBA's public stats website and are not guaranteed to work.

Hope that answers your question!
