### ISSUE TITLE
Missing draft number and draft round in http://nbasense.com/nba-api/Data/MobileTeams/Player/PlayerCard#request-request-info

### ISSUE THREAD

**Issue by Lokoko01** [jasonroman/nba-stats-api#8]
Hello,

Will you add this information soon ?

Thks

**Comment by jasonroman** [comment]
Hello,

Could you elaborate on what you mean?

**Comment by jasonroman** [comment]
Closing as no additional information given.  I am assuming you mean the data does not have draft number/round for players, but I do not determine what is returned by the data.  This API is a tool to help access NBA data which I do not have control over.

Thanks,
-Jason
